### ISSUE TITLE
请教在BoringSSL中添加sm算法的方式

### ISSUE THREAD

**Issue by MadaoChan** [zhenyuwei/Guomi#2]
大佬您好，看到您在这个repo上的回复
https://github.com/guanzhi/GmSSL/issues/1103

其中您说到直接在boringssl中添加国密代码即可
目前我参照了GmSSL在boringssl中已经加入了国密相关的oid定义
但若不把算法实现移植过去的话，国密应该不起作用？

然而往BoringSSL中添加算法的文章又实在少，故冒昧在此请教下sm算法移植的话应该需要怎么做才对。
感谢！

**Comment by zhenyuwei** [comment]
算法添加可参考boringssl内已有的，直接将OpenSSL的SM算法代码拷贝进去，协议参考GmSSL的代码与BoringSSL的TLSv1.1流程

**Comment by MadaoChan** [comment]
感谢回复～
之前试着把sm系列算法都copy进去了，但不是很懂要怎么定义EVP接口之类的东西
然后加密套件之类的应该也要重新去弄？不知道前辈有没有相关的文章可以参考下

今天试着直接把gmssl的库内置进去chromium了，然后去替换boringssl的include
编译时遇到redefinition的问题，若把所有相关include都更换一遍的话，这样做不知是否可行……

**Comment by zhenyuwei** [comment]
> 感谢回复～ 之前试着把sm系列算法都copy进去了，但不是很懂要怎么定义EVP接口之类的东西 然后加密套件之类的应该也要重新去弄？不知道前辈有没有相关的文章可以参考下
> 
> 今天试着直接把gmssl的库内置进去chromium了，然后去替换boringssl的include 编译时遇到redefinition的问题，若把所有相关include都更换一遍的话，这样做不知是否可行……

建议在BoringSSL上修改，后续升核都非常方便，主要研究添加SM算法在BorinSSL里面对应算法的实现方式（例如SM4参考AES，SM3参考SHA256），网上应该有文章可以参考的。

**Comment by MadaoChan** [comment]
> > 感谢回复～ 之前试着把sm系列算法都copy进去了，但不是很懂要怎么定义EVP接口之类的东西 然后加密套件之类的应该也要重新去弄？不知道前辈有没有相关的文章可以参考下
> > 今天试着直接把gmssl的库内置进去chromium了，然后去替换boringssl的include 编译时遇到redefinition的问题，若把所有相关include都更换一遍的话，这样做不知是否可行……
> 
> 建议在BoringSSL上修改，后续升核都非常方便，主要研究添加SM算法在BorinSSL里面对应算法的实现方式（例如SM4参考AES，SM3参考SHA256），网上应该有文章可以参考的。

网上有位前辈做了个gm-boringssl，但他只做了sm3，sm4只有一个cbc模式
我试着再加了一个sm4的ctr模式
请问是否必须要把sm4所有模式都实现了才能正常使用呢？

然后到sm2的时候，代码是移进去了
应该是要改ec目录里面的东西去调用sm2，但具体改哪些东西没有概念……
boringssl跟gmssl虽说都是从openssl而来但两边文件结构的差距还是有点大的
经常移着移着就出现同名文件定义冲突的情况，这条路目前就卡在这里，不知道怎么办好

谢谢！

**Comment by zhenyuwei** [comment]
crypto\fipsmodule 目录下参考aes目录添加sm4目录，参考sha目录添加sm3目录，参考ec目录添加sm2目录，对应的算法代码都是独立的，头文件信息参考aes.h/sha.h/ec.h，添加后看看bcm.c文件。对于GM协议，0024-201只用到了CBC套件，最新的38636-2020用到了GCM和CCM套件。
有问题留下你的联系方式。

**Comment by MadaoChan** [comment]
> crypto\fipsmodule 目录下参考aes目录添加sm4目录，参考sha目录添加sm3目录，参考ec目录添加sm2目录，对应的算法代码都是独立的，头文件信息参考aes.h/sha.h/ec.h，添加后看看bcm.c文件。对于GM协议，0024-201只用到了CBC套件，最新的38636-2020用到了GCM和CCM套件。 有问题留下你的联系方式。

谢谢解答！
QQ 441429593

**Comment by rm888888** [comment]
大佬，我最近也是想在chromium里面支持国密证书，请教下怎么个流程将gmssl的东西移植到boringssl呢，目前没有什么概念

**Comment by lmz2423** [comment]
这个有交流群吗
